<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-SetlistPlaylistCreator.WebApi-e97a3721-3173-4a27-a805-b8a23687189e</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="6.0.18" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="6.0.18" />
    <PackageReference Include="Microsoft.Identity.Web" Version="1.16.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SetlistPlaylistCreator.SetlistPlatform\SetlistPlaylistCreator.SetlistPlatform.csproj" />
    <ProjectReference Include="..\SetlistPlaylistCreator.StreamingPlatform.Spotify\SetlistPlaylistCreator.StreamingPlatform.Spotify.csproj" />
    <ProjectReference Include="..\SetlistPlaylistCreator.StreamingPlatform\SetlistPlaylistCreator.StreamingPlatform.csproj" />
    <ProjectReference Include="..\Spotify.Client\Spotify.Client.csproj" />
  </ItemGroup>

</Project>
